FROM eclipse-temurin:11-jdk-noble

ARG version=10.6.4
ARG download_url="https://maven.ontotext.com/repository/owlim-releases/com/ontotext/graphdb/graphdb/${version}/graphdb-${version}-dist.zip"
ARG download_url_checksum="${download_url}.md5"

# Downloading the required packages
RUN apt-get update && \
    apt-get install -u unzip

RUN adduser graphdb

# Downloading GraphDB
RUN curl -fsSL "${download_url}" > graphdb-${version}-dist.zip && \
    bash -c 'md5sum -c - <<<"$(curl -fsSL ${download_url_checksum})  graphdb-${version}-dist.zip"' && \
    unzip graphdb-${version}-dist.zip && \
    rm -f graphdb-${version}-dist.zip


RUN mv graphdb-${version} graphdb && \
    chown -R graphdb /graphdb && \
    mkdir "/opt/graphdb" && \
    chown -R graphdb /opt/graphdb && \
    mkdir "graphdb/lib/jdbc" && \
    curl https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.2.0/mysql-connector-j-9.2.0.jar -o /graphdb/lib/jdbc/mysql-jdbc.jar

# Creating the folders for the data, logs and backup folders of GraphDB
RUN mkdir -p "/shared-volume/graphdb/data/repositories" && \
    mkdir -p "/shared-volume/graphdb/logs" && \
    mkdir -p "/shared-volume/graphdb/backups" && \
    chown -R graphdb /shared-volume/graphdb && \
    chmod -R 777 /shared-volume/graphdb/data/repositories


USER graphdb

ENTRYPOINT ["/graphdb/bin/graphdb"]

CMD ["-Dgraphdb.home=/opt/graphdb/home", "-Dgraphdb.distribution=docker", "-Dgraphdb.home.data=/shared-volume/graphdb/data", "-Dgraphdb.home.logs=/shared-volume/graphdb/logs"]

EXPOSE 7200
EXPOSE 7300