FROM alpine:latest

RUN adduser -u 1001 graphdb --ingroup users -D && \
    mkdir -p "shared-volume/graphdb-project/python" && \
    mkdir -p "shared-volume/graphdb-project" && \
    mkdir -p "shared-volume/graphdb-project/graphdb" && \
    mkdir -p "shared-volume/graphdb-project/mysql/data/scripts" && \
    mkdir -p "shared-volume/graphdb-project/mysql/start" && \
    mkdir -p "shared-volume/graphdb-project/mysql/init" && \
    chown -R 1001 "shared-volume/graphdb-project"

COPY init-entrypoint.sh /
COPY init-healthcheck.sh /

CMD ["./init-entrypoint.sh"]