services:
  init:
    build:
      dockerfile: Dockerfile-init
    volumes:
      - shared-volume:/shared-volume
    networks:
      - graphdbnetwork
    healthcheck:
      test: [ "CMD", "/init-healthcheck.sh" ]
      retries: 3
      interval: 2s
  graphdb:
    build:
      dockerfile: Dockerfile-graphdb
    ports:
      - "0:7200"
    volumes:
      - type: volume
        source: shared-volume
        target: /shared-volume-graphdb
        volume:
          subpath: graphdb-project/graphdb
      - type: volume
        source: shared-volume
        target: /shared-volume-python
        volume:
          subpath: graphdb-project/python

    container_name: "graphdb"
    networks:
      - graphdbnetwork
    healthcheck:
      test: [ "CMD", "/graphdb-healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      init:
        condition: service_healthy

  python:
    build:
      dockerfile: Dockerfile-python
    volumes:
      - type: volume
        source: shared-volume
        target: /shared-volume-python
        volume:
          subpath: graphdb-project/python
      - type: volume
        source: shared-volume
        target: /shared-volume-graphdb
        volume:
          subpath: graphdb-project/graphdb
      - type: volume
        source: shared-volume
        target: /shared-volume-mysql
        volume:
          subpath: graphdb-project/graphdb
    env_file:
      - vars.env
    container_name: "python"
    ports:
      - "0:8000"
    networks:
      - graphdbnetwork
    depends_on:
      # mysql:
      #  condition: service_healthy
      graphdb:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1


  mysql:
    build:
      dockerfile: Dockerfile-mysql
    ports:
      - '0:3306'
    volumes:
      - type: volume
        source: shared-volume
        target: /docker-entrypoint-initdb.d
        volume:
          subpath: graphdb-project/mysql/init
      - type: volume
        source: shared-volume
        target: /docker-entrypoint-startdb.d
        volume:
          subpath: graphdb-project/mysql/start
      - type: volume
        source: shared-volume
        target: /shared-volume-python
        volume:
          subpath: graphdb-project/python
    environment:
      - MYSQL_Database=database
      - MYSQL_ROOT_PASSWORD=root
      - BITNAMI_DEBUG=true
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      retries: 10
    stop_grace_period: 30s
    networks:
      - graphdbnetwork
    depends_on:
      init:
        condition: service_healthy
volumes:
  shared-volume:
    name: "shared-volume"
    external: true
  mysql:

networks:
  graphdbnetwork:
