FROM docker.io/bitnami/mysql:8.4
USER root
RUN mkdir "/exec" && chown -R 1001 /exec

COPY ./mysql-entrypoint.sh /opt/bitnami/scripts/mysql
COPY evo.sh /exec/

RUN chmod +x /opt/bitnami/scripts/mysql/mysql-entrypoint.sh && \
    mkdir -p /graphdb-project && \
    touch /graphdb-project/done.sh &&  \
    chown -R 1001 /graphdb-project

USER 1001
EXPOSE 3306
ENTRYPOINT [ "/opt/bitnami/scripts/mysql/mysql-entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/mysql/run.sh" ]