FROM alpine:latest

RUN adduser -u 1001 graphdb --ingroup users -D && \
    mkdir -p "shared-volume/graphdb-project/python" && \
    mkdir -p "shared-volume/graphdb-project/graphdb" && \
    mkdir -p "shared-volume/graphdb-project/graphdb/backups" && \
    mkdir -p "shared-volume/graphdb-project/graphdb/data/repositories" && \
    mkdir -p "shared-volume/graphdb-project/mysql/start" && \
    mkdir -p "shared-volume/graphdb-project/mysql/init" && \
    chown -R graphdb "shared-volume/graphdb-project"

COPY evo.sh /
COPY init-entrypoint.sh /

RUN chmod +x /init-entrypoint.sh

CMD ["./init-entrypoint.sh"]