services:
  graphdb:
    build:
      dockerfile: Dockerfile-graphdb
    ports:
      - "0:7200"
    volumes:
      - shared-volume:/shared-volume
    container_name: "graphdb"
    networks:
      - graphdbnetwork
    healthcheck:
      test: [ "CMD-SHELL", "grep 'Started GraphDB' /shared-volume/graphdb/logs/main.logs" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  python:
    build:
      dockerfile: Dockerfile-python
    volumes:
      - shared-volume:/shared-volume
    container_name: "python"
    networks:
      - graphdbnetwork
    depends_on:
      - graphdb
volumes:
  shared-volume:
    name: shared-volume
    external: true

networks:
  graphdbnetwork:
