services:
  graphdb:
    build:
      dockerfile: Dockerfile
    ports:
      - "0:7200"
    volumes:
      - shared-volume:/shared-volume

volumes:
  shared-volume:
    name: shared-volume
    external: true
