FROM python:3.13-alpine

RUN python -m venv /config/python_env && \
    adduser -u 1001 --ingroup users -D python && \
    echo "python:python" | chpasswd


RUN mkdir -p /exec && \
    mkdir -p /shared-volume-python && \
    mkdir -p /shared-volume-graphdb && \
    mkdir -p /config && \
    mkdir /django && \
    chown -R python /exec && \
    chown -R python /shared-volume-graphdb && \
    chown -R python /shared-volume-python && \
    chown -R python /config/python_env && \
    chown -R python /django

COPY entrypoint.sh evo.sh /exec/


# Setting up Django
COPY ./graphdbform  /django/

USER 1001

ENTRYPOINT ["/exec/entrypoint.sh"]